version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
on:
jobs:
artifacts:
  files:
    - backend.yml
    - target/*.jar
  discard-paths: yes
